  - name: "Install prerequisites"
    apt: 
      name: '{{ item }}'
      state: latest
    loop: 
      - aptitude

  - name: Install pyMySQL
    pip:
      name: pymysql
      state: present
    ignore_errors: True
  - name: check status of nginx
    service:
        name: nginx
        state: stopped
    register: nginx_status
    when: http_server == "apache2"

  - name: Print nginx service status
    debug:
          msg: "nginx service is {{ 'started' if nginx_status.status == 'started' else 'stopped' }}"
    when: http_server == "apache2"

    